config/routes.rb
Testem::Application.routes.draw do

  devise_for :users
  resources :quizzes, only: [:show, :index] do
    resources :solutions, only: [:new]
  end
  resources :solutions, only: [:create, :show, :index] do
    get :deliver, on: :member
  end

  namespace :admin do
    resources :quizzes
    resources :users
    root to: 'quizzes#index'
  end

  root to: 'quizzes#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question, touch: true

  validates :text, presence: true

  default_scope -> { order(:created_at) }

end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :quiz, touch: true
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true

  default_scope -> { order(:created_at) }

  validates :text, presence: true
  
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base

  has_many :questions, dependent: :destroy
  has_many :quiz_versions

  alias_method :versions, :quiz_versions

  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

  validates :name, presence: true

  def current_version 
    if versions.last && versions.last.created_at >= updated_at
      versions.last
    else
      versions.create
    end
  end

  def as_json(options = default_json_options)
    super
  end

  def to_json(options = default_json_options)
    super
  end

private

  def default_json_options
    {
      only: [:name],
      include: {
        questions: {
          only: [:text],
          include: {
            answers: {
              only: [:text, :correct]
            }
          }
        }
      }
    }
  end
end

app/models/quiz_version.rb
class QuizVersion < ActiveRecord::Base
  belongs_to :quiz
  has_many :solutions

  validates :quiz, presence: true

  before_save :populate_content
  before_save :compute_total

  default_scope -> { order(created_at: :desc, id: :desc) }

  def questions
    decoded[:questions].map do |question|
      SimpleQuiz::Question.new(question)
    end
  end

  def name
    decoded[:name]
  end

  def decoded
    @decoded ||= ActiveSupport::JSON.decode(content, symbolize_names: true)
  end

private

  def populate_content
    self.content = quiz.to_json
  end

  def compute_total
    self.total = quiz.questions.reduce(0) { |sum, question| sum + question.answers.count }
  end
end

app/models/simple_quiz/answer.rb
module SimpleQuiz
  class Answer
    attr_accessor :text, :correct

    def initialize(attributes = {})
      self.text = attributes[:text]
      self.correct = attributes[:correct]
    end

    def persisted?
      false
    end
  end
end

app/models/simple_quiz/question.rb
module SimpleQuiz
  class Question
    attr_accessor :text
    attr_reader :answers

    def initialize(attributes)
      self.text = attributes[:text]
      self.answers = attributes[:answers]
    end

    def answers=(hash)
      @answers = hash.map do |answer|
        SimpleQuiz::Answer.new(answer)
      end
    end

    def persisted?
      false
    end
  end
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :quiz_version
  belongs_to :user

  validates_presence_of :user, :quiz_version, :answers

  before_save :compute_mark

  def answers=(hash)
    temp = hash.values.map { |e| e['answers'].values.map { |e| !e['response'].to_i.zero? } }
    write_attribute(:answers, ActiveSupport::JSON.encode(temp))
  end

  def decoded
    @decoded ||= ActiveSupport::JSON.decode(self[:answers])
  end

  def final_mark
    "#{mark.to_i}/#{quiz_version.total.to_i}"
  end

private

  def compute_mark
    mark = 0
    quiz_version.questions.each_with_index do |question, question_index| 
      question.answers.each_with_index do |answer, answer_index|
        mark += 1 if decoded[question_index][answer_index] == answer.correct
      end
    end
    self.mark = mark
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :solutions
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_permission!

  private

  def verify_permission!
    unless current_user.try(:admin?)
      redirect_to root_path, alert: 'You are not authorized.'
    end
  end
end

app/controllers/admin/quizzes_controller.rb
class Admin::QuizzesController < Admin::BaseController
  before_action :find_quiz_with_includes, only: [:edit, :update, :destroy]

  def index
    @quizzes = Quiz.all
  end

  def new
    @quiz = Quiz.new
    @quiz.questions.build.answers.build()
  end

  def create
    @quiz = Quiz.new(quiz_params)
    if @quiz.save!
      redirect_to admin_quiz_path(@quiz), notice: 'Quiz created successfully'
    else
      render 'new'
    end
  end

  def show
    @quiz = Quiz.includes(questions: :answers, quiz_versions: {}).find(params[:id])
  end

  def edit
  end

  def update
    if @quiz.update(quiz_params)
      redirect_to admin_quiz_path(@quiz), notice: 'Quiz updated successfully'
    else
      render 'edit'
    end
  end

  def destroy
    @quiz.destroy
    redirect_to admin_quizzes_path, notice: 'Quiz removed'
  end

private

  def find_quiz
    @quiz = Quiz.find(params[:id])
  end

  def find_quiz_with_includes
    @quiz = Quiz.includes(questions: :answers).find(params[:id])
  end
  
  def quiz_params
    params.require(:quiz).permit(:name, questions_attributes: [:id, :text, :_destroy, answers_attributes: [:id, :text, :correct, :_destroy]])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :find_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user == current_user
      redirect_to admin_user_path(@user), alert: 'You cannot edit yourself, try editing your profile'
    else
      if @user.update(user_params)
        redirect_to admin_user_path(@user), notice: 'User updated.'
      else
        render 'edit'
      end
    end
  end

private
  
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:admin)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @quizzes = Quiz.all
  end

  def show
    @quiz = Quiz.includes(questions: :answers).find(params[:id])
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :authenticate_user!

  def new
    @quiz = Quiz.includes(questions: :answers, quiz_versions: {}).find(params[:quiz_id]).current_version
  end

  def create
    @quiz_version = QuizVersion.find(solution_params[:id])
    @solution = @quiz_version.solutions.build(answers: solution_params[:questions].to_hash, user: current_user)
    if @solution.save
      redirect_to @solution
    else
      render 'new'
    end
  end

  def show
    @solution = current_user.solutions.find(params[:id])
  end

  def index
    @solutions = current_user.solutions.includes(:quiz_version).load
  end

  def deliver
    @solution = current_user.solutions.includes(:quiz_version).find(params[:id])
    if UserMailer.solution(@solution).deliver
      redirect_to @solution, notice: 'Email delivered'
    else
      redirect_to @solution, alert: "Email couldn't be delivered"
    end
  end

private

  def solution_params
    params.require(:quiz_version).permit(:id, questions: [answers: [:response]])
  end
end

app/helpers/admin/quizzes_helper.rb
module Admin::QuizzesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/views/admin/quizzes/_answer_fields.html.haml
.nested-fields.row.answer
  .col-md-8= f.input :text, as: :string, label: 'Answer', label_html: { class: 'sr-only' }, placeholder: 'Answer'
  .col-md-2= f.input :correct, label_html: { style: 'margin-top: 5px;' }
  .col-md-2= link_to_remove_association 'Remove answer', f, { class: 'btn btn-danger btn-block' }

app/views/admin/quizzes/_form.html.haml
= simple_form_for [:admin, quiz] do |f|
  = f.input :name, as: :string
  %h3 Questions
  .questions
    = f.simple_fields_for :questions do |fq|
      = render 'question_fields', f: fq
    .links
      = link_to_add_association 'Add question', f, :questions, { class: 'btn btn-default' }
  = f.submit submit, class: 'btn btn-primary'

app/views/admin/quizzes/_question_fields.html.haml
.nested-fields.question
  .row
    .col-md-2= link_to_remove_association 'Remove question', f, { class: 'btn btn-danger btn-block' }
    .col-md-10= f.input :text, as: :string, label: 'Question', label_html: { class: 'sr-only' }, placeholder: 'Question'
  .row
    .col-md-10.col-md-offset-2
      %h4 Answers
      .answers
        = f.simple_fields_for :answers do |fa|
          = render 'answer_fields', f: fa
        .links
          = link_to_add_association 'Add answer', f, :answers, { class: 'btn btn-default' }

app/views/admin/quizzes/_quiz.html.haml
%tr.quiz
  %td= quiz.id
  %td= link_to quiz.name, admin_quiz_path(quiz)
  %td
    = link_to 'Edit', edit_admin_quiz_path(quiz)
    = link_to 'Delete', admin_quiz_path(quiz), method: :delete, data: { confirm: 'Are you shure?' }

app/views/admin/quizzes/edit.html.haml
%h2 Edit quiz

= render 'form', quiz: @quiz, submit: 'Save'

app/views/admin/quizzes/index.html.haml
%h2 All currently available quizzes

%table.table
  %tr
    %th Id
    %th Name
    %th Actions
  = render @quizzes

= link_to 'Create new', new_admin_quiz_path, class: 'btn btn-default'

app/views/admin/quizzes/new.html.haml
%h2 Create new quiz

= render 'form', quiz: @quiz, submit: 'Create'

app/views/admin/quizzes/show.html.haml
.quiz.row
  .col-md-12
    %h2= @quiz.name
    .row
      .col-md-2
        = link_to 'Edit quiz', edit_admin_quiz_path(@quiz), class: 'btn btn-default btn-block'
        %br
        = link_to 'Remove quiz', admin_quiz_path(@quiz), method: 'delete', class: 'btn btn-danger btn-block', data: { confirmation: 'Are you shure?' }
      .col-md-10
        .panel.panel-primary
          .panel-heading
            %h4.panel-title Current state
          .panel-body
            - @quiz.questions.each_with_index do |question, index|
              .question.row
                .col-lg-12
                  %p= "#{index+1}. #{question.text}"
                  %ul.answers
                    - question.answers.each do |answer|
                      %li.answer{class: (answer.correct ? 'correct' : 'incorrect')}= answer.text
        - @quiz.versions.each_with_index do |quiz_version, qv_index|
          .panel.panel-default
            .panel-heading
              %h4.panel-title= quiz_version.created_at
            .panel-body
              - quiz_version.questions.each_with_index do |question, index|
                .question.row
                  .col-lg-12
                    %p= "#{index+1}. #{question.text}"
                    %ul.answers
                      - question.answers.each do |answer|
                        %li.answer{class: (answer.correct ? 'correct' : 'incorrect')}= answer.text

app/views/admin/users/_user.html.haml
%tr.user
  %td= user.id
  %td= link_to user.email, admin_user_path(user)
  %td= (user.admin ? 'True' : 'False')
  %td
    = link_to 'Edit', edit_admin_user_path(user)

app/views/admin/users/edit.html.haml
%h2 Edit user

.row
  .col-md-12
    %p 
      User:
      = @user.email
    = simple_form_for [:admin, @user] do |f|
      = f.input :admin
      = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/users/index.html.haml
%h2 All users

%table.table
  %tr
    %th Id
    %th Email
    %th Admin
    %th Actions
  = render @users

app/views/admin/users/show.html.haml
%h2
  User:
  = @user.email
.user.row
  .col-md-2
    = link_to 'Edit user', edit_admin_user_path(@user), class: 'btn btn-default btn-block'
  .col-md-10
    %p.lead
      Admin:
      = @user.admin ? 'True' : 'False'
    - %w[ created_at updated_at remember_created_at current_sign_in_at last_sign_in_at sign_in_count current_sign_in_ip last_sign_in_ip].each do |property|
      %p= "#{property.humanize}: #{@user.send(property)}"

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Testem', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %p.navbar-text= 'Welcome admin' if current_user.try(:admin?)
      %ul.nav.navbar-nav.pull-right
        = render 'layouts/navigation_links'
      - if current_user.try(:admin?)
        %ul.nav.navbar-nav.pull-left
          = render 'layouts/navigation_admin_links'

app/views/layouts/_navigation_admin_links.html.haml
%li= link_to 'Quizzes', admin_quizzes_path
%li= link_to 'Users', admin_users_path

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to('Solutions', solutions_path) %>
  </li>
  <li>
  <%= link_to('Edit profile', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Testem'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Testem'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/quizzes/_quiz.html.haml
%li.quiz
  %p= link_to quiz.name, quiz

app/views/quizzes/index.html.haml
%h2 All currently available quizzes

%ul.lead
  = render @quizzes

app/views/quizzes/show.html.haml
.quiz.row
  .col-md-12
    %h2= @quiz.name
    .row
      .col-md-2
        = link_to 'Solve quiz', new_quiz_solution_path(@quiz), class: 'btn btn-primary btn-block'
      .col-md-10
        - @quiz.questions.each_with_index do |question, index|
          .question.row
            .col-lg-12
              %p= "#{index+1}. #{question.text}"
              %ul
                - question.answers.each do |answer|
                  %li.answer= answer.text

app/views/solutions/index.html.haml
%h2 Your solved quizzes

%ul
  - @solutions.each do |solution|
    %li.solution= link_to solution.quiz_version.name, solution

app/views/solutions/new.html.haml
.quiz.row
  .col-md-12
    %h2= @quiz.name
    .row
      .col-md-2
        %p.text-muted Please remember it's a multiple-choice test. Consider carefully each answer whether it's true or false. Good luck!
      .col-md-10
        = simple_form_for @quiz, url: solutions_path(@quiz.quiz), method: :post do |f|
          = f.input :id, as: :hidden
          - @quiz.questions.each_with_index do |question, question_index|
            = f.simple_fields_for "questions[#{question_index}]" do |fq|
              .question.row
                .col-md-12
                  %p= "#{question_index+1}. #{question.text}"
                  %ul
                    - question.answers.each_with_index do |answer, answer_index|
                      = fq.simple_fields_for "answers[#{answer_index}]" do |fa|
                        = fa.input :response, as: :boolean, label: answer.text, input_html: { checked: false }
          .links
            = f.submit 'Save', class: 'btn btn-primary'

app/views/solutions/show.html.haml
.quiz.row
  .col-md-12
    %h2= @solution.quiz_version.name
    .row
      .col-md-2
        %p.lead
          Mark:
          = @solution.final_mark
        = link_to 'Deliver results email', deliver_solution_path(@solution), class: 'btn btn-primary'
      .col-md-10
        - @solution.quiz_version.questions.each_with_index do |question, question_index|
          .question.row
            .col-lg-12
              %p= "#{question_index+1}. #{question.text}"
              %ul.answers
                - question.answers.each_with_index do |answer, answer_index|
                  %li.answer{class: [(answer.correct ? 'correct' : 'incorrect'), (@solution.decoded[question_index][answer_index] == answer.correct ? 'good' : 'bad')]}= answer.text